### PR TITLE
Rename BookList to BookCollection

### PR DESCRIPTION
**Pull request by Ty-stan0417**

### CODE REVIEW

**Review by jinhanfromNUS — COMMENTED** [review]
Awesome changes

**Review by jinhanfromNUS — COMMENTED** [review]
Can you change the attributes to BookCollection? It will allow easier development in the future!

**Comment by Ty-stan0417** [comment]
> Can you change the attributes to BookCollection? It will allow easier development in the future!

Yes, I think this is a good suggestion, I have change it. Please help me see again whether is good to you.

**Comment by jinhanfromNUS** [comment]
> > Can you change the attributes to BookCollection? It will allow easier development in the future!
> 
> Yes, I think this is a good suggestion, I have change it. Please help me see again whether is good to you.

Awesome! Your code looks great.

**Review by jinhanfromNUS — APPROVED** [review]
LGTM!

**Pull request merged**
